[grid]
max_bottleneck_utilization = [0.75, 0.80, 0.85, 0.90, 0.95, 1.0]
absolute_lateness_ratio = [0.25, 0.5, 0.75, 1.0]
inner_tardiness_ratio = [1.0, 0.75, 0.5, 0.25, 0.0]
simulation_sigma = [0.2, 0.4, 0.6]

[run]
source_name = "Fisher and Thompson 10x10"
shift_length = 1440
total_shift_number = 28

